"""Synthetic demo run generation."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from segevo.logger import SegEvoLogger


def generate_demo_run(out: str | Path, epochs: int = 8, cases: int = 3) -> Path:
    out_path = Path(out)
    logger = SegEvoLogger(
        out_path,
        manifest={
            "project": "SegEvo synthetic demo",
            "task": "binary_2d_toy_segmentation",
            "classes": ["background", "lesion"],
            "spacing": [1.0, 1.0],
            "note": "Generated by segevo-demo.",
        },
        spacing=(1.0, 1.0),
    )

    for case_index in range(cases):
        image, gt = _make_case(seed=case_index)
        for epoch in range(epochs):
            pred = _make_prediction(gt, epoch=epoch, total_epochs=epochs, seed=case_index)
            logger.log_case(
                epoch=epoch,
                case_id=f"case_{case_index + 1:03d}",
                image=image,
                gt=gt,
                pred=pred,
                features={
                    "bottleneck": _fake_feature_map(image, gt, pred, epoch, epochs),
                },
            )
    return out_path


def _make_case(seed: int, size: int = 128) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    yy, xx = np.mgrid[:size, :size]
    center_y = rng.integers(size // 3, 2 * size // 3)
    center_x = rng.integers(size // 3, 2 * size // 3)
    radius_y = rng.integers(15, 24)
    radius_x = rng.integers(18, 28)
    gt = (((yy - center_y) / radius_y) ** 2 + ((xx - center_x) / radius_x) ** 2 <= 1).astype(
        np.uint8
    )
    image = 0.18 + 0.18 * rng.normal(size=(size, size))
    image += 0.55 * gt
    image += 0.12 * np.sin(xx / 12.0) + 0.08 * np.cos(yy / 15.0)
    return image.astype(np.float32), gt


def _make_prediction(gt: np.ndarray, epoch: int, total_epochs: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(10_000 + seed * 100 + epoch)
    progress = epoch / max(total_epochs - 1, 1)
    structure = np.ones((3, 3), dtype=bool)
    mask = gt.astype(bool)

    if progress < 0.35:
        mask = _shift(mask, dy=5 - epoch, dx=-4 + epoch)
        mask = nd_binary_dilate(mask, iterations=3)
    elif progress < 0.7:
        mask = nd_binary_dilate(mask, iterations=1)
    else:
        mask = mask.copy()

    noise = rng.random(gt.shape)
    false_positive = noise < (0.045 * (1.0 - progress))
    false_negative = (noise > 1.0 - 0.035 * (1.0 - progress)) & mask
    mask = (mask | false_positive) & ~false_negative

    if progress > 0.5:
        from scipy import ndimage

        mask = ndimage.binary_opening(mask, structure=structure)
    return mask.astype(np.uint8)


def nd_binary_dilate(mask: np.ndarray, iterations: int) -> np.ndarray:
    from scipy import ndimage

    return ndimage.binary_dilation(mask, iterations=iterations)


def _shift(mask: np.ndarray, dy: int, dx: int) -> np.ndarray:
    shifted = np.zeros_like(mask)
    src_y = slice(max(0, -dy), mask.shape[0] - max(0, dy))
    src_x = slice(max(0, -dx), mask.shape[1] - max(0, dx))
    dst_y = slice(max(0, dy), mask.shape[0] - max(0, -dy))
    dst_x = slice(max(0, dx), mask.shape[1] - max(0, -dx))
    shifted[dst_y, dst_x] = mask[src_y, src_x]
    return shifted


def _fake_feature_map(
    image: np.ndarray,
    gt: np.ndarray,
    pred: np.ndarray,
    epoch: int,
    total_epochs: int,
) -> np.ndarray:
    from scipy import ndimage

    progress = epoch / max(total_epochs - 1, 1)
    gt_b = gt > 0
    pred_b = pred > 0
    structure = ndimage.generate_binary_structure(gt.ndim, 1)
    gt_boundary = gt_b ^ ndimage.binary_erosion(gt_b, structure=structure, border_value=0)
    boundary_band = ndimage.binary_dilation(gt_boundary, structure=structure, iterations=2)
    near_foreground = ndimage.binary_dilation(gt_b, structure=structure, iterations=8)
    false_positive = pred_b & ~gt_b
    false_negative = gt_b & ~pred_b
    hard_background = near_foreground & ~gt_b & ~false_positive

    yy, xx = np.mgrid[: gt.shape[0], : gt.shape[1]]
    xx = xx.astype(np.float32) / max(gt.shape[1] - 1, 1)
    yy = yy.astype(np.float32) / max(gt.shape[0] - 1, 1)
    image_norm = (image - float(np.min(image))) / max(float(np.ptp(image)), 1e-6)

    return np.stack(
        [
            image_norm,
            gt_b.astype(np.float32) * (0.65 + 0.35 * progress),
            pred_b.astype(np.float32) * (0.35 + 0.65 * progress),
            boundary_band.astype(np.float32) * (0.45 + 0.55 * progress),
            hard_background.astype(np.float32) * (1.0 - 0.25 * progress),
            false_positive.astype(np.float32) * (1.0 - progress)
            - false_negative.astype(np.float32) * (1.0 - progress),
            xx,
            yy,
        ],
        axis=0,
    ).astype(np.float32)
